<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1a2c99b4-b9df-473f-befa-25c004d81fae</UserSecretsId>
  </PropertyGroup>



  <ItemGroup>
    <ProjectReference Include="..\ReservaCanchas.Application\ReservaCanchas.Application.csproj" />
    <ProjectReference Include="..\ReservaCanchas.Infrastructure\ReservaCanchas.Infrastructure.csproj" />
    <ProjectReference Include="..\ReservaCanchas.Contracts\ReservaCanchas.Contracts.csproj" />
  </ItemGroup>



  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

</Project>
